framework/app/Http/routes.php
<?php

/* Authentication/Resiter routes */
// Auth::routes();


Route::post('register',[
  'as'=>'post_register',
  'uses'=>'Auth\AuthController@postRegister'
  ]);

Route::get('login',[
  'as'=>'post_login',
  'uses'=>'Auth\AuthController@postLogin'
  ]);



// Route::get('login', ['as' => 'post_login' , function($request){

//   var_dump($request);
// }]);



Route::post('login',[
  'as'=>'post_login',
  'uses'=>'Auth\AuthController@postLogin'
  ]);



Route::get('logout',[ 
  'as'=> 'get_logout', 
  'uses'=> 'Auth\AuthController@getLogout'
  ]);


Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\PasswordController@reset');

Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::get('/admin' , 'SiteController@adminview');


/*Users profile route */

Route::resource('profile', 'UsersController');

//new pravin
Route::any('display/latestvideos' , ['uses'=>'HomeController@getdata']);
Route::any('display/plainlatestvideos/{section}' , ['uses'=>'HomeController@videolatestplain']);


// Route::any('upload/show' , ['uses'=>'HomeController@userdata']);
// Route::post('upload/add',['uses'=>'uploadcontroller@uploadfile']);

Route::any('upload' , 'UploadsController@input');
Route::post('uploads/store','UploadsController@store');
Route::get('upload/show','UploadsController@index');
Route::delete('uploads/{type}/{id}','UploadsController@destroy');
Route::get('uploads/{type}/{id}','UploadsController@edit');
Route::post('uploads/{type}/{id}','UploadsController@update');

Route::any('search' , ['uses'=>'HomeController@search']);
Route::any('suggest' , ['uses'=>'HomeController@suggest']);

Route::post('privacy' , 'UploadsController@privacy_check');

//croppic controller
Route::get('test','UploadController@getTest');
Route::post('avtupload', 'UploadController@postUpload');
Route::post('avtcrop', 'UploadController@postCrop');

get('/',['uses'=>'SiteController@index']);
// get('index.html',['uses'=>'SiteController@playerCanvas']);

Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');

get('image/channel/{Name}' ,'SiteController@channel_image');
get('channel/{channel_name}',['uses'=>'SiteController@channel']);
get('subchannel/{channel_name}',['uses'=>'SiteController@subchannel']);
get('termsofservice',['uses'=>'SiteController@termsofservice']);
get('privacypolicy',['uses'=>'SiteController@privacypolicy']);
get('about-us',['uses'=>'SiteController@aboutUs']);
get('feature-video',['uses'=>'SiteController@featureVideo']);
get('promoted-video',['uses'=>'SiteController@promotedVideo']);
get('detail/{id}',['uses'=>'SiteController@detailVideo']);
get('image/{id}',['uses'=>'SiteController@detailImage']);

get('full/{id}',['uses'=>'SiteController@fullVideo']);
//
post('detail/{id}',['uses'=>'SiteController@detailVideo']);
get('search-videos',['uses'=>'SiteController@searchVideos']);
get('video/playbackurl/{id}','HomeController@playBackUrl');
get('demo',['uses'=>'SiteController@demo']);
get('videos/{id}/{string}',['uses'=>'SiteController@videoById']);
get('channel/subchannel/{channel_id}','\Videochautari\Channel\Controllers\ChannelController@subChannel');



Route::post('display/latestplainvideos' , ['uses'=>'SiteController@subchannelplain']);

Route::any('categories', ['uses'=>'HomeController@categories']);
Route::any('json/categories', ['uses'=>'HomeController@jsonCategories']);
Route::any('json/categories2', ['uses'=>'HomeController@jCategories']);
Route::any('detailplain/{id}',['uses'=>'SiteController@detailplainVideo']);


Route::any('categories_total.php', ['uses'=>'HomeController@categories']);
Route::any('videos_list_total.php', ['uses'=>'HomeController@videoListTotal']);

Route::any('playlist-all.php', ['uses'=>'HomeController@playListAll']);

//categories_total.php jsonVideoListTotal_2
Route::any('json/videos-list-total/{channel_id}', ['uses'=>'HomeController@jsonVideoListTotal']);
Route::any('json/videos-list-total/{channel_id}', ['uses'=>'HomeController@jsonVideoListTotal']);
Route::any('json/videos-list-totall/{channel_id}', ['uses'=>'HomeController@jsonVideoListTotall']);

Route::get('api/categories_nonyoutube',['uses'=>'HomeController@nonYoutubeCategories']);
Route::get('categories_nonyoutube.php',['uses'=>'HomeController@nonYoutubeCategories']);

//
//http://www.videochautari.com/?channel_id=150

Route::get('api/videos_nonyoutube',['uses'=>'HomeController@nonYoutubeVideos']);
Route::get('videos_nonyoutube.php',['uses'=>'HomeController@nonYoutubeVideos']);

Route::any('config', ['uses'=>'HomeController@Config']);



Route::any('videos-list-total/{channel_id}', ['uses'=>'HomeController@videoListTotal']);



// Route::get('admin',function(){
//         return view('admin.auth.login');

// });


Route::get('welcome',function(){
        return "you are welcome!!!";

});

Route::get('dashboard',function(){
    return view('admin.dashboard');
});


Route::post('auth/login', 'AdminController@postLogin');
//Route::post('front/login', 'FrontUserController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');
//Route::post('auth/login',function(){
//    return "post";
//});

//Admin section
Route::group(['prefix' => 'dashboard'], function () {
   Route::resource('channels','\Videochautari\Channel\Controllers\ChannelController');
   Route::resource('videos','\Videochautari\Video\Controllers\VideoController');
   Route::resource('images','\Videochautari\Video\Controllers\ImageController');
Route::get('videos\delete\{id}','\Videochautari\Video\Controllers\VideoController@delete');

    Route::resource('types','\Videochautari\Channel\Controllers\TypeController');
    Route::get('channels/{channel_id}/addsubchannel',['uses'=>'\Videochautari\Channel\Controllers\ChannelController@addSubChannel']);
    Route::get('channels/{channel_id}/viewsubchannel',['uses'=>'\Videochautari\Channel\Controllers\ChannelController@viewSubChannel']);
    Route::post('channels/{channel_id}/addsubchannel',['uses'=>'\Videochautari\Channel\Controllers\ChannelController@subchannelStore','as'=>'admin.subchannels.store']);
    Route::post('videos/add-video',['uses'=>'\Videochautari\Video\Controllers\VideoController@addVideo','as'=>'admin.addvideo']);

});

Route::post('file-upload','UploadsController@dropzone');
Route::post('file-upload-thumb/{type}','UploadsController@dropzone2');
Route::post('file-upload-video/{type}','UploadsController@dropzone3');




Route::get('session/upload_store','UploadsController@data_store');
Route::get('session/user','UploadsController@user_data');


Route::get('360image/{name}' , 'SiteController@imagechannel');
Route::get('360video/{name}' , 'SiteController@videochannel');

// auto complete

// Route::get('search',array('as'=>'search','uses'=>'SearchController@search'));
// Route::get('autocomplete',array('as'=>'autocomplete','uses'=>'SearchController@autocomplete'));

Route::get('add/user' , 'UsersController@adduser');
Route::post('add/userdata' , 'UsersController@user_data_add');
Route::get('edit/user' , 'UsersController@edituser');
Route::post('/delete_user' , 'UsersController@deleteuser');


// route for channel butoon option 
 Route::post('display/channeloption/{option}'  , 'HomeController@channeloption');

framework/app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['first_name','last_name', 'email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function images(){
        return $this->hasMany('App\Image');
    }

    public function videos(){
        return $this->hasMany('App\Video');
    }

    public function subchannels(){
        return $this->hasMany('App\SubChannel');
    }
}

framework/app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Auth;
use App\User;
use Hash;
use App\Video;
use App\Image;
use App\Channel;
use Intervention\Image\ImageManagerStatic as Img;

class UsersController extends Controller
{
    protected $video;

    protected $image;
    protected $channel;

    public function __construct(Video $video,Image $image, Channel $channel){
        $this->video = $video;
        $this->image = $image;
        $this->channel = $channel;
        $user = \Auth::user();
        if ( is_null( $user )){
          return view('home.session_end');
        }
    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {    
     $user = \Auth::user();
     if ( is_null( $user )){
          return view('home.session_end');
    }
    
         $user=Auth::user();
         $videos = $this->video->orderBy('date_uploaded','DESC')->where('user_id',"=",$user->id)->paginate(30);
         $images = $this->image->orderBy('date_uploaded','DESC')->where('user_id',"=",$user->id)->paginate(30);

      
        return view('user.index',compact('user','videos','images'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {    

        $user = \Auth::user();
            if ( is_null( $user )){
              return view('home.session_end');
            }

        if($request->hasFile('avatar')){
            $avatar = $request->file('avatar');
            $extension2 = $avatar->getClientOriginalExtension();
            // $new = uniqid();
            // dd($new);
            ini_set('memory_limit','256M');
            // dd($extension2);
            $filename = uniqid().'.'.$extension2;
            Img::make($avatar)->resize(300, 200)->save('uploads/avatars/'.$filename);
            // $request->file('avatar')->move('uploads/avatars',$filename);

            $user=Auth::user();
            $user->avatar = $filename;
            // $user->save();
        }

        $first_name = $request->input('first_name');
        $last_name = $request->input('last_name');
        $user->first_name = $first_name;
        $user->last_name = $last_name;
        $user->save();


        return redirect()->action('UploadsController@index');
        

    }

    public function adduser(Request $request){

       $user = \Auth::user();
            if ( is_null( $user )){
              return view('home.admin');
            }
        return view('home.adduser');
        

    }
   
   public function user_data_add(Request $request){

        $user_match = User::where('email' , $request->email)->first();
        
        if($user_match){
            $request->session()->flash('status' , 'no');
            return view('home.adduser');
        }
        $request->merge(['password'=>Hash::make($request->password) , 'key'=>12]);
        $user = \App\User::create($request->all());
        return view('home.added');
   
   }

   public function edituser(Request $request){

        $user_admin = User::where('role' , 1)->get();
        $user = User::where('role' , 0)->get();
        return view('home.user_list' , ['useradmin'=>$user_admin , 'user'=> $user]);
   }


   public function deleteuser(Request $request){

        $user = User::find($request->user_id)->delete();

   }
   
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

framework/resources/views/user/index.blade.php
@extends('master')

@section('title_page')
 ParacosmaTV | 360 Videos
@stop 

@section('content')
	<div class="container">
		<div class="row">
		{{-- {{ $user->images}} --}}
			<div class="col-md-10 col-md-offset-1">
				<img src="{{asset('/uploads/avatars/'.$user->avatar)}}" style="width:150px; height:150px; float:left; border-radius:50%; margin-right:25px;">

				<form enctype="multipart/form-data" action="{{route('profile.store')}}" method="POST">
				{{csrf_field()}}
					<label>Update Profile Image</label>
					<input type="file" name="avatar">
					<input type="submit" class="pull-right btn btn-sm btn-primary">

				</form>
				<h2>{{ $user->first_name}}'s Profile</h2>
			</div>
		</div>
	</div>


                 <div class="sections">
                        <h2 class="heading">User content List</h2>
                        <div class="clearfix"></div>
                       
                            
                            @foreach($user->videos->chunk(3) as $chunk)
                             <div class="row">
                            @foreach($chunk as $video)   
                            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12"> 
                                <!-- Video Box Start -->
                                <div class="videobox2">
                                    <figure> 
                                        <!-- Video Thumbnail Start --> 
                                        <a href="{{url("detail/$video->indexer")}}">
                                            <img src="{{ asset('uploads/'.$video->video_id.'.'.$video->thumb) }}" class="img-responsive hovereffect" alt="" />
                                        </a> 
                                        <!-- Video Thumbnail End --> 
                                        <!-- Video Info Start -->
                                        <div class="vidopts">
                                            <ul>
                                                <li><i class="fa fa-heart"></i>{{$video->number_of_views}}</li>
                                                <li><i class="fa fa-clock-o"></i>{{$video->video_length}}</li>
                                            </ul>
                                            <div class="clearfix"></div>
                                        </div>
                                       <!-- Video Info End --> 
                                    </figure>
                                    <!-- Video Title Start -->
                                    <h4><a href="{{url("detail/$video->indexer")}}">{{str_limit($video->title,30)}}</a></h4>
                                    <!-- Video Title End --> 
                                </div>
                                <!-- Video Box End --> 
                            </div>
                            <ul class="categories hidden-md hidden-lg">
                                <li style="padding: 5px 10px; border-bottom: 1px solid #fff; margin-bootm: 4px; font-size: 16px;">
                                <a style="font-weight: normal; font-size: 14px; color: #1F97D4" href="{{url("detail/$video->indexer")}}">{{str_limit($video->title,35)}}</a></li>
                            </ul>
                            @endforeach
                             </div>
                            @endforeach
                          {!! $videos->render() !!}
                       
                    </div> 
                    <div class="link">
                @foreach($user->images->chunk(4) as $chunk)
                            <div class="row">
                            @foreach($chunk as $feature)
                          
                                 <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 hidden-xs hidden-sm featured-width "> 
                                      <!-- Video Box Start -->
                                      <div class="videobox2">
                                          <figure> 
                                        
                                          <iframe
                                          frameborder="0"
                                          width="100%"
                                          height=290px
                                          scrolling="no"
                                          allowfullscreen    
                                          src="vrview/index.html?image={{asset('uploads/'.$feature->image_id. '.' .$feature->type)}}  &is_stereo=true"> 
                                          
                                          </iframe>
                                        
                                              <!-- Video Thumbnail Start --> 
                                              
                                               
                                          </figure>
                                          <!-- Video Title Start -->
                                          
                                          <span class=" mli-info " style="background: url('/paracosmatv/images/mask-title.png') top repeat-x;">
                                            <h4 class="category-name" style="color: white !important;">{{(App\Channel::find($feature->channel_id)->channel_name)}}</h4>
                                            <a href="{{url('detail/$feature->indexer')}}" >{{str_limit($feature->title,10)}}</a></span>
                                          
                                          <!-- <span>
                                            Channel: {{(App\Channel::find($feature->channel_id)->channel_name)}}
                                          </span> -->
                                          
                                          <!-- Video Title End --> 
                                      </div>
                                      <!-- Video Box End --> 
                                  </div>
                              
                            
              <ul class="categories hidden-md hidden-lg">
                <li style="padding: 5px 10px; border-bottom: 1px solid #fff; margin-bootm: 4px; font-size: 16px;">
                <a style="font-weight: bold; font-size: 14px; color: #1F97D4" href="{{url('detail/$feature->indexer')}}">{{str_limit($feature->title,35)}}</a></li>
              </ul>
                        @endforeach

                        </div>
             @endforeach
             </div>
@stop
@section('sidebar')

@include('home.sidebar')

@stop