framework/app/Http/routes.php
<?php

/* Authentication/Resiter routes */
// Auth::routes();


Route::post('register',[
  'as'=>'post_register',
  'uses'=>'Auth\AuthController@postRegister'
  ]);

Route::get('login',[
  'as'=>'post_login',
  'uses'=>'Auth\AuthController@postLogin'
  ]);



// Route::get('login', ['as' => 'post_login' , function($request){

//   var_dump($request);
// }]);



Route::post('login',[
  'as'=>'post_login',
  'uses'=>'Auth\AuthController@postLogin'
  ]);



Route::get('logout',[ 
  'as'=> 'get_logout', 
  'uses'=> 'Auth\AuthController@getLogout'
  ]);


Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\PasswordController@reset');

Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::get('/admin' , 'SiteController@adminview');


/*Users profile route */

Route::resource('profile', 'UsersController');

//new pravin
Route::any('display/latestvideos' , ['uses'=>'HomeController@getdata']);
Route::any('display/plainlatestvideos/{section}' , ['uses'=>'HomeController@videolatestplain']);


// Route::any('upload/show' , ['uses'=>'HomeController@userdata']);
// Route::post('upload/add',['uses'=>'uploadcontroller@uploadfile']);

Route::any('upload' , 'UploadsController@input');
Route::post('uploads/store','UploadsController@store');
Route::get('upload/show','UploadsController@index');
Route::delete('uploads/{type}/{id}','UploadsController@destroy');
Route::get('uploads/{type}/{id}','UploadsController@edit');
Route::post('uploads/{type}/{id}','UploadsController@update');

Route::any('search' , ['uses'=>'HomeController@search']);
Route::any('suggest' , ['uses'=>'HomeController@suggest']);

Route::post('privacy' , 'UploadsController@privacy_check');

//croppic controller
Route::get('test','UploadController@getTest');
Route::post('avtupload', 'UploadController@postUpload');
Route::post('avtcrop', 'UploadController@postCrop');

get('/',['uses'=>'SiteController@index']);
// get('index.html',['uses'=>'SiteController@playerCanvas']);

Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');

get('image/channel/{Name}' ,'SiteController@channel_image');
get('channel/{channel_name}',['uses'=>'SiteController@channel']);
get('subchannel/{channel_name}',['uses'=>'SiteController@subchannel']);
get('termsofservice',['uses'=>'SiteController@termsofservice']);
get('privacypolicy',['uses'=>'SiteController@privacypolicy']);
get('about-us',['uses'=>'SiteController@aboutUs']);
get('feature-video',['uses'=>'SiteController@featureVideo']);
get('promoted-video',['uses'=>'SiteController@promotedVideo']);
get('detail/{id}',['uses'=>'SiteController@detailVideo']);
get('image/{id}',['uses'=>'SiteController@detailImage']);

get('full/{id}',['uses'=>'SiteController@fullVideo']);
//
post('detail/{id}',['uses'=>'SiteController@detailVideo']);
get('search-videos',['uses'=>'SiteController@searchVideos']);
get('video/playbackurl/{id}','HomeController@playBackUrl');
get('demo',['uses'=>'SiteController@demo']);
get('videos/{id}/{string}',['uses'=>'SiteController@videoById']);
get('channel/subchannel/{channel_id}','\Videochautari\Channel\Controllers\ChannelController@subChannel');



Route::post('display/latestplainvideos' , ['uses'=>'SiteController@subchannelplain']);

Route::any('categories', ['uses'=>'HomeController@categories']);
Route::any('json/categories', ['uses'=>'HomeController@jsonCategories']);
Route::any('json/categories2', ['uses'=>'HomeController@jCategories']);
Route::any('detailplain/{id}',['uses'=>'SiteController@detailplainVideo']);


Route::any('categories_total.php', ['uses'=>'HomeController@categories']);
Route::any('videos_list_total.php', ['uses'=>'HomeController@videoListTotal']);

Route::any('playlist-all.php', ['uses'=>'HomeController@playListAll']);

//categories_total.php jsonVideoListTotal_2
Route::any('json/videos-list-total/{channel_id}', ['uses'=>'HomeController@jsonVideoListTotal']);
Route::any('json/videos-list-total/{channel_id}', ['uses'=>'HomeController@jsonVideoListTotal']);
Route::any('json/videos-list-totall/{channel_id}', ['uses'=>'HomeController@jsonVideoListTotall']);

Route::get('api/categories_nonyoutube',['uses'=>'HomeController@nonYoutubeCategories']);
Route::get('categories_nonyoutube.php',['uses'=>'HomeController@nonYoutubeCategories']);

//
//http://www.videochautari.com/?channel_id=150

Route::get('api/videos_nonyoutube',['uses'=>'HomeController@nonYoutubeVideos']);
Route::get('videos_nonyoutube.php',['uses'=>'HomeController@nonYoutubeVideos']);

Route::any('config', ['uses'=>'HomeController@Config']);



Route::any('videos-list-total/{channel_id}', ['uses'=>'HomeController@videoListTotal']);



// Route::get('admin',function(){
//         return view('admin.auth.login');

// });


Route::get('welcome',function(){
        return "you are welcome!!!";

});

Route::get('dashboard',function(){
    return view('admin.dashboard');
});


Route::post('auth/login', 'AdminController@postLogin');
//Route::post('front/login', 'FrontUserController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');
//Route::post('auth/login',function(){
//    return "post";
//});

//Admin section
Route::group(['prefix' => 'dashboard'], function () {
   Route::resource('channels','\Videochautari\Channel\Controllers\ChannelController');
   Route::resource('videos','\Videochautari\Video\Controllers\VideoController');
   Route::resource('images','\Videochautari\Video\Controllers\ImageController');
Route::get('videos\delete\{id}','\Videochautari\Video\Controllers\VideoController@delete');

    Route::resource('types','\Videochautari\Channel\Controllers\TypeController');
    Route::get('channels/{channel_id}/addsubchannel',['uses'=>'\Videochautari\Channel\Controllers\ChannelController@addSubChannel']);
    Route::get('channels/{channel_id}/viewsubchannel',['uses'=>'\Videochautari\Channel\Controllers\ChannelController@viewSubChannel']);
    Route::post('channels/{channel_id}/addsubchannel',['uses'=>'\Videochautari\Channel\Controllers\ChannelController@subchannelStore','as'=>'admin.subchannels.store']);
    Route::post('videos/add-video',['uses'=>'\Videochautari\Video\Controllers\VideoController@addVideo','as'=>'admin.addvideo']);

});

Route::post('file-upload','UploadsController@dropzone');
Route::post('file-upload-thumb/{type}','UploadsController@dropzone2');
Route::post('file-upload-video/{type}','UploadsController@dropzone3');




Route::get('session/upload_store','UploadsController@data_store');
Route::get('session/user','UploadsController@user_data');


Route::get('360image/{name}' , 'SiteController@imagechannel');
Route::get('360video/{name}' , 'SiteController@videochannel');

// auto complete

// Route::get('search',array('as'=>'search','uses'=>'SearchController@search'));
// Route::get('autocomplete',array('as'=>'autocomplete','uses'=>'SearchController@autocomplete'));

Route::get('add/user' , 'UsersController@adduser');
Route::post('add/userdata' , 'UsersController@user_data_add');
Route::get('edit/user' , 'UsersController@edituser');
Route::post('/delete_user' , 'UsersController@deleteuser');


// route for channel butoon option 
 Route::post('display/channeloption/{option}'  , 'HomeController@channeloption');

framework/app/Video.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    protected $primaryKey = 'indexer';

    protected $fillable = ['video_id',
        'type',
        'response_id',
        'channel_id',
        'sub_channel_id',
        'user_id',
        'viewtime',
        'title',
        'title_seo',
        'description',
        'tags',
        'channel',
        'date_uploaded',
        'location_recorded',
        'video_length',
        'allow_comments',
        'allow_embedding',
        'allow_ratings',
        'approved',
        'featured',
        'promoted',
        'flag_counter',
        'video_type',
        'thumb'
    ];
    public $timestamps = false;

  
    
    public function scopeFlaggedItem($query,$flag,$value){
    	return $query->where($flag,'=',$value);
    }

    public static  function boot(){
        parent::boot();
        static::creating(function($model){
            $model->date_uploaded = date('Y-m-d H:i:s');
        });
    }

 protected $dates = ['date_uploaded'];

    public function channel()
    {
        return $this->belongsTo('App\Channel','channel_id');
    }
    public function comments(){
    	return $this->hasMany('App\Comment','video_id');
    }

    public function subchannel()
    {
        return $this->belongsTo('App\SubChannel','sub_channel_id');
    }

    public function user()
    {
        return $this->belongsTo('App\User','user_id');
    }
}

framework/resources/views/admin/videos/_form.blade.php
      {!! csrf_field() !!}
      <!--  <div class="form-group">
      <label class="label-control" for="">Video Type</label>

      {!! Form::select('type',[''=>'--Select a format--','mp4'=>'mp4', 'm4v'=>'m4v'],null,['class'=>'form-control']); !!}
      </div> -->
      <div class="form-group">
            <label class="label-control" for="">Channel Name</label>
            {!! Form::select('channel_id',$channels,null,['class'=>'form-control channel_id']); !!}
      </div>


      <div class="form-group">
            <label class="label-control" for="">Channel Name</label>
            {!! Form::select('sub_channel_id',$sub_channels,null,['class'=>'form-control sub_channel_id']); !!}
      </div>

      <div class="form-group">
            <label class="label-control" for="">Title</label>
            {!! Form::text('title',null,['class'=>'form-control']); !!}
      </div>

      <div class="form-group">
            <label class="label-control" for="">Title Seo</label>
            {!! Form::text('title_seo',null,['class'=>'form-control']); !!}
      </div>

      <div class="form-group">
            <label class="label-control" for="">Description</label>
            {!! Form::textarea('description',null,['class'=>'form-control']); !!}
      </div>

      <div class="form-group">
            <label class="label-control" for="">Video Length</label>
            {!! Form::text('video_length',null,['class'=>'form-control']); !!}
      </div>

      <div class="form-group">
            <label class="label-control" for="">Tags</label>
            {!! Form::textarea('tags',null,['class'=>'form-control tags']); !!}
      </div>

      <div class="form-group">
            <label class="label-control" for="">Feature</label>
            {!! Form::select('featured',['yes'=>'yes','no'=>'no'],null,['class'=>'form-control featured']); !!}
      </div>

      <div class="form-group">
            <label class="label-control" for="">Promoted</label>
            {!! Form::select('promoted',['yes'=>'yes','no'=>'no'],null,['class'=>'form-control promoted']); !!}
      </div>

      
      <div class="form-group">
            <label class="label-control" for="">Choose Image to upload</label>
            <input type="file" name="image">
      </div>
      <div class="form-group">
            <label class="label-control" for="">Choose Video to upload</label>
            <input type="file" name="video">
      </div>

      <div class="form-group">
      <input type="submit" name="submit" value="Save" class="btn btn-danger"/>
      </div>

framework/resources/views/admin/videos/edit.blade.php
@extends('admin.master')
@section('css')
<link href="{{ asset('assets/css/style.css') }}" rel="stylesheet" />
@stop

@section('content')

<div class="uploading" style="display:none;">
                       <img src="{{asset('images/loading.gif')}}" alt=""/>
    			</div>
    <
{!! Form::model($video, ['route' => ['dashboard.videos.update', $video->indexer]]) !!}
<input type="hidden" name="_method" value="PATCH" />
        @include('admin.videos._form')
    </form>


@stop
@section('script')

<script>
$(document).ready(function(){
    $('#browser').on('click',function(){
        $('.uploading').css('display','block');
    });

    $('.channel_id').on('change',function(){
        var channel_id = $(this).val();
console.log(channel_id);
        $.ajax({
            url: "{{url('channel/subchannel')}}/"+channel_id,
            type: "GET",
            data: {channel_id:channel_id},
            success: function(res){
            var option = '';
            if(res.length >= 1){
              $.each(res,function(id,obj){
                    option += "<option value='"+obj.sub_channel_id+"'>";
                    option += obj.sub_channel_name;
                    option += "</option>";
              });

            } else {
                 option += "<option value=''>";
                option += '--Sub channel not added--';
                option += "</option>";
            }


               $('.sub_channel_id').html(option);
            }

        });
    });
});


</script>




@stop

framework/resources/views/admin/videos/index.blade.php
@extends('admin.master')
@section('content')
    <a href="{{url('dashboard/videos/create')}}" class="btn btn-primary">Create</a>
    <table class="table table-bordered">
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>date_created</th>
            <th>Video Length</th>
            <th>Length</th>
            <th>Action</th>
        </tr>
        @foreach($videos as $video)
            <tr>
                <td>{{$video->title}}</td>
                <td>{{$video->description}}</td>
                <td>{{$video->date_uploaded}}</td>
                <td>{{$video->video_length}}</td>
                <td><img class="img-responsive" width="200" height="200" src="{{asset('uploads/'.$video->video_id.'.'.$video->thumb)}}" /></td>
                <td>
                    <a href="{{url('dashboard/videos/'.$video->indexer.'/update')}}">Edit</a>
		                <a href="{{url('dashboard/videos/delete/'.$video->indexer)}}">Delete</a>

               </td>
            </tr>
        @endforeach
    </table>
{!! $videos->render() !!}

@stop

framework/resources/views/admin/videos/new.blade.php
@extends('admin.master')
@section('css')
<link href="{{ asset('assets/css/style.css') }}" rel="stylesheet" />
@stop

@section('content')

<div class="uploading" style="display:none;">
    <img src="{{asset('images/loading.gif')}}" alt=""/>
</div>
    <form id="videoForm" action="{{route('dashboard.videos.store')}}" enctype="multipart/form-data" method="post">
        @include('admin.videos._form')
    </form>


@stop
@section('script')

<script>
$(document).ready(function(){
    $('#browser').on('click',function(){
        $('.uploading').css('display','block');
    });

    $('.channel_id').on('change',function(){
        var channel_id = $(this).val();
console.log(channel_id);
        $.ajax({
            url: "{{url('channel/subchannel')}}/"+channel_id,
            type: "GET",
            data: {channel_id:channel_id},
            success: function(res){
            var option = '';
            if(res.length >= 1){
              $.each(res,function(id,obj){
                    option += "<option value='"+obj.sub_channel_id+"'>";
                    option += obj.sub_channel_name;
                    option += "</option>";
              });

            } else {
                 option += "<option value=''>";
                option += '--Sub channel not added--';
                option += "</option>";
            }


               $('.sub_channel_id').html(option);
            }

        });
    });
});


</script>




@stop